services:
  vasie-dev:
    # Use this for production (pulls from registry)
    # For GHCR: ghcr.io/USERNAME/REPO:tag
    image: ${IMAGE_NAME:-ghcr.io/vasie/vasie-dev}:${IMAGE_TAG:-latest}
    
    # Uncomment below for local development (builds from source)
    # build:
    #   context: .
    #   dockerfile: DockerFile
    
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    container_name: vasie-dev
