services:
  portfolio:
    image: ${DOCKER_REGISTRY}/${GITHUB_OWNER}/portfolio:latest
    container_name: ${INSTANCE_NAME}
    restart: always
    environment:
      - NODE_ENV=${ENVIRONMENT}
      - INSTANCE_NAME=${INSTANCE_NAME}
    volumes:
      - app-data:/data
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ${INSTANCE_NAME}-cloudflared
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - app-network

volumes:
  app-data:
    name: ${INSTANCE_NAME}-data

networks:
  app-network:
    name: ${INSTANCE_NAME}-network
    driver: bridge
    labels:
      com.docker.compose.network: "app-network"