services:
  vasie-dev:
    # Use this for production (pulls from registry)
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_IMAGE_NAME:-vasie-dev}:${IMAGE_TAG:-latest}
    
    # Uncomment below for local development (builds from source)
    # build:
    #   context: .
    #   dockerfile: DockerFile
    
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    container_name: vasie-dev
