name: Reusable Configuration

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'production'
        type: string
      instance_name:
        description: 'Instance name'
        required: false
        type: string
    outputs:
      project_name:
        description: 'Project name'
        value: ${{ jobs.config.outputs.project_name }}
      environment:
        description: 'Environment'
        value: ${{ jobs.config.outputs.environment }}
      instance_name:
        description: 'Instance name'
        value: ${{ jobs.config.outputs.instance_name }}
      short_sha:
        description: 'Short SHA'
        value: ${{ jobs.config.outputs.short_sha }}

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.set-outputs.outputs.project_name }}
      environment: ${{ steps.set-outputs.outputs.environment }}
      instance_name: ${{ steps.set-outputs.outputs.instance_name }}
      short_sha: ${{ steps.set-outputs.outputs.short_sha }}
    
    steps:
      - name: Set configuration outputs
        id: set-outputs
        run: |
          echo "project_name=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
          echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          echo "instance_name=${{ inputs.instance_name || github.event.repository.name }}" >> $GITHUB_OUTPUT
          echo "short_sha=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT 