###########################################
# Configuration Stage
###########################################
name: 1. Configure Deployment

###########################################
# Workflow Triggers
###########################################
on:
  # Deploy on push to main branches
  push:
    branches: [ main, master ]
  
  # Manual workflow trigger with options
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development
      instance_name:
        description: 'Instance name (defaults to repository name if not specified)'
        required: false
        type: string

###########################################
# Jobs
###########################################
jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.set-vars.outputs.project_name }}
      environment: ${{ steps.set-vars.outputs.environment }}
      instance_name: ${{ steps.set-vars.outputs.instance_name }}
      short_sha: ${{ steps.set-vars.outputs.short_sha }}
      
    steps:
      #---------------------------------------
      # Checkout Repository
      #---------------------------------------
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Shallow clone for faster checkout
      
      #---------------------------------------
      # Set Configuration Variables
      #---------------------------------------
      - name: Set environment variables
        id: set-vars
        run: |
          # Set environment variables
          PROJECT_NAME="${{ github.event.repository.name }}"
          ENVIRONMENT="${{ github.event.inputs.environment || 'production' }}"
          INSTANCE_NAME="${{ github.event.inputs.instance_name || github.event.repository.name }}"
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          
          # Set outputs for next workflows
          echo "project_name=$PROJECT_NAME" >> $GITHUB_OUTPUT
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "instance_name=$INSTANCE_NAME" >> $GITHUB_OUTPUT
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "build_date=$BUILD_DATE" >> $GITHUB_OUTPUT
      
      #---------------------------------------
      # Trigger Build Workflow
      #---------------------------------------
      - name: Trigger Build Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 2. Build Docker Image
          token: ${{ secrets.GITHUB_TOKEN }} 