name: Deploy to VPS

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'production'
        type: string
      instance_name:
        description: 'Instance name'
        required: false
        type: string
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      ENVIRONMENT: ${{ inputs.environment }}
      INSTANCE_NAME: ${{ inputs.instance_name || github.event.repository.name }}
      SHORT_SHA: ${{ inputs.image_tag }}
    
    steps:
      # Setup SSH for VPS deployment
      - name: Checkout code for env files
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      
      - name: Generate Docker Compose file
        run: |
          # Create a Docker Compose file with environment variables
          COMPOSE_CONTENT=$(cat << EOF
          version: '3.8'
          
          services:
            ${INSTANCE_NAME}:
              image: ${{ secrets.DOCKER_USERNAME }}/${PROJECT_NAME}:${SHORT_SHA}
              container_name: ${INSTANCE_NAME}-${ENVIRONMENT}
              restart: always
              environment:
                - NODE_ENV=${ENVIRONMENT}
                - INSTANCE_NAME=${INSTANCE_NAME}
              volumes:
                - ${INSTANCE_NAME}-${ENVIRONMENT}-data:/data
              networks:
                - ${INSTANCE_NAME}-${ENVIRONMENT}-network
              # Optional port mapping - uncomment and customize as needed
              # ports:
              #  - "\${PORT_PREFIX}80:80"  # You can define PORT_PREFIX in repository secrets
          
            ${INSTANCE_NAME}-cloudflared:
              image: cloudflare/cloudflared:latest
              container_name: ${INSTANCE_NAME}-${ENVIRONMENT}-cloudflared
              restart: always
              command: tunnel run
              environment:
                - TUNNEL_TOKEN=${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
              networks:
                - ${INSTANCE_NAME}-${ENVIRONMENT}-network
          
          volumes:
            ${INSTANCE_NAME}-${ENVIRONMENT}-data:
              name: ${INSTANCE_NAME}-${ENVIRONMENT}-data
          
          networks:
            ${INSTANCE_NAME}-${ENVIRONMENT}-network:
              name: ${INSTANCE_NAME}-${ENVIRONMENT}-network
              driver: bridge
          EOF
          )
          
          # Write the content to a file
          echo "$COMPOSE_CONTENT" > docker-compose.${ENVIRONMENT}-${INSTANCE_NAME}.yml
      
      - name: Copy files and deploy to VPS
        run: |
          # Create project directory structure with instance separation
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p ~/deployments/${PROJECT_NAME}/${ENVIRONMENT}/${INSTANCE_NAME}"
          
          # Copy docker-compose file
          scp docker-compose.${ENVIRONMENT}-${INSTANCE_NAME}.yml ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/deployments/${PROJECT_NAME}/${ENVIRONMENT}/${INSTANCE_NAME}/docker-compose.yml
          
          # Copy environment-specific env file if it exists
          if [ -f ".env.${ENVIRONMENT}" ]; then
            scp .env.${ENVIRONMENT} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/deployments/${PROJECT_NAME}/${ENVIRONMENT}/${INSTANCE_NAME}/.env.environment
          fi
          
          # Copy instance-specific env file if it exists
          if [ -f ".env.${INSTANCE_NAME}" ]; then
            scp .env.${INSTANCE_NAME} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/deployments/${PROJECT_NAME}/${ENVIRONMENT}/${INSTANCE_NAME}/.env.instance
          fi
          
          # Copy combined env file if it exists
          if [ -f ".env.${ENVIRONMENT}.${INSTANCE_NAME}" ]; then
            scp .env.${ENVIRONMENT}.${INSTANCE_NAME} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/deployments/${PROJECT_NAME}/${ENVIRONMENT}/${INSTANCE_NAME}/.env
          fi
          
          # Deploy service with custom pull policy to avoid unnecessary pulls
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ~/deployments/${PROJECT_NAME}/${ENVIRONMENT}/${INSTANCE_NAME} && docker-compose pull && docker-compose up -d --remove-orphans"
          
          # More targeted cleanup - only remove dangling images and ones not used by current deployment
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "docker image prune -f && docker container prune -f" 