name: Deploy
on:
  workflow_call:
    inputs:
      service_names:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true
      VPS_USER:
        required: true
      VPS_PASSWORD:
        required: true
      VPS_IP:
        required: true

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Prepare Environment
      run: |
        chmod +x .github/scripts/prepare-deployment.sh
        ./.github/scripts/prepare-deployment.sh
    
    - name: Deploy to VPS
      run: |
        chmod +x .github/scripts/deploy-to-vps.sh
        ./.github/scripts/deploy-to-vps.sh
      env: 
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        VPS_IP: ${{ secrets.VPS_IP }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}