name: Deploy to VPS

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'production'
        type: string
      instance_name:
        description: 'Instance name'
        required: false
        type: string
      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      ENVIRONMENT: ${{ inputs.environment }}
      INSTANCE_NAME: ${{ inputs.instance_name || github.event.repository.name }}
      SHORT_SHA: ${{ inputs.image_tag }}
    
    steps:
      # Setup SSH for VPS deployment
      - name: Checkout code for env files
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      
      - name: Generate Docker Compose file
        run: |
          cat > docker-compose.${{ env.ENVIRONMENT }}-${{ env.INSTANCE_NAME }}.yml << 'EOL'
          version: '3.8'
          
          services:
            ${{ env.INSTANCE_NAME }}:
              image: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ env.SHORT_SHA }}
              container_name: ${{ env.INSTANCE_NAME }}-${{ env.ENVIRONMENT }}
              restart: always
              environment:
                - NODE_ENV=${{ env.ENVIRONMENT }}
                - INSTANCE_NAME=${{ env.INSTANCE_NAME }}
              volumes:
                - ${{ env.INSTANCE_NAME }}-${{ env.ENVIRONMENT }}-data:/data
              networks:
                - ${{ env.INSTANCE_NAME }}-${{ env.ENVIRONMENT }}-network
              # Optional port mapping - uncomment and customize as needed
              # ports:
              #  - "${PORT_PREFIX}80:80"  # You can define PORT_PREFIX in repository secrets
          
            ${{ env.INSTANCE_NAME }}-cloudflared:
              image: cloudflare/cloudflared:latest
              container_name: ${{ env.INSTANCE_NAME }}-${{ env.ENVIRONMENT }}-cloudflared
              restart: always
              command: tunnel run
              environment:
                - TUNNEL_TOKEN=${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
              networks:
                - ${{ env.INSTANCE_NAME }}-${{ env.ENVIRONMENT }}-network
          
          volumes:
            ${{ env.INSTANCE_NAME }}-${{ env.ENVIRONMENT }}-data:
              name: ${{ env.INSTANCE_NAME }}-${{ env.ENVIRONMENT }}-data
          
          networks:
            ${{ env.INSTANCE_NAME }}-${{ env.ENVIRONMENT }}-network:
              name: ${{ env.INSTANCE_NAME }}-${{ env.ENVIRONMENT }}-network
              driver: bridge
          EOL
      
      - name: Copy files and deploy to VPS
        run: |
          # Create project directory structure with instance separation
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "mkdir -p ~/deployments/${{ env.PROJECT_NAME }}/${{ env.ENVIRONMENT }}/${{ env.INSTANCE_NAME }}"
          
          # Copy docker-compose file
          scp docker-compose.${{ env.ENVIRONMENT }}-${{ env.INSTANCE_NAME }}.yml ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/deployments/${{ env.PROJECT_NAME }}/${{ env.ENVIRONMENT }}/${{ env.INSTANCE_NAME }}/docker-compose.yml
          
          # Copy environment-specific env file if it exists
          if [ -f ".env.${{ env.ENVIRONMENT }}" ]; then
            scp .env.${{ env.ENVIRONMENT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/deployments/${{ env.PROJECT_NAME }}/${{ env.ENVIRONMENT }}/${{ env.INSTANCE_NAME }}/.env.environment
          fi
          
          # Copy instance-specific env file if it exists
          if [ -f ".env.${{ env.INSTANCE_NAME }}" ]; then
            scp .env.${{ env.INSTANCE_NAME }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/deployments/${{ env.PROJECT_NAME }}/${{ env.ENVIRONMENT }}/${{ env.INSTANCE_NAME }}/.env.instance
          fi
          
          # Copy combined env file if it exists
          if [ -f ".env.${{ env.ENVIRONMENT }}.${{ env.INSTANCE_NAME }}" ]; then
            scp .env.${{ env.ENVIRONMENT }}.${{ env.INSTANCE_NAME }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/deployments/${{ env.PROJECT_NAME }}/${{ env.ENVIRONMENT }}/${{ env.INSTANCE_NAME }}/.env
          fi
          
          # Deploy service with custom pull policy to avoid unnecessary pulls
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ~/deployments/${{ env.PROJECT_NAME }}/${{ env.ENVIRONMENT }}/${{ env.INSTANCE_NAME }} && docker-compose pull && docker-compose up -d --remove-orphans"
          
          # More targeted cleanup - only remove dangling images and ones not used by current deployment
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "docker image prune -f && docker container prune -f" 