# DEPRECATED - See the new workflow structure
#
# This workflow has been split into multiple files for better modularity:
# - main.yml: Main CI/CD pipeline that runs on pushes to main/master
# - manual-deploy.yml: Manual deployment with additional options
# - config.yml: Reusable workflow for configuration
# - build.yml: Reusable workflow for Docker image building
# - deploy-vps.yml: Reusable workflow for VPS deployment
#
# Please use the new workflow files instead of this one.

name: Deploy to VPS (DEPRECATED)

on:
  workflow_dispatch:
    inputs:
      redirect:
        description: 'This workflow is deprecated. Please use "Manual Deployment" workflow instead.'
        required: true
        default: 'understand'
        type: choice
        options:
          - understand

jobs:
  inform:
    runs-on: ubuntu-latest
    steps:
      - name: Inform about deprecation
        run: |
          echo "This workflow is deprecated. Please use the new workflow structure:"
          echo "- main.yml: Main CI/CD pipeline"
          echo "- manual-deploy.yml: Manual deployment with additional options"
          echo "- config.yml: Reusable workflow for configuration"
          echo "- build.yml: Reusable workflow for Docker image building"
          echo "- deploy-vps.yml: Reusable workflow for VPS deployment"