name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development
      instance_name:
        description: 'Instance name (defaults to repository name if not specified)'
        required: false
        type: string

jobs:
  # Get configuration
  config:
    uses: ./.github/workflows/config.yml
    with:
      environment: ${{ github.event.inputs.environment || 'production' }}
      instance_name: ${{ github.event.inputs.instance_name }}

  # Build Docker image
  build:
    needs: config
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ needs.config.outputs.environment }}
      instance_name: ${{ needs.config.outputs.instance_name }}
    secrets: inherit
  
  # Deploy to VPS
  deploy:
    needs: [config, build]
    uses: ./.github/workflows/deploy-vps.yml
    with:
      environment: ${{ needs.config.outputs.environment }}
      instance_name: ${{ needs.config.outputs.instance_name }}
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets: inherit 