name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development
      instance_name:
        description: 'Instance name (defaults to repository name)'
        required: false
        type: string
      skip_build:
        description: 'Skip build and use existing image'
        required: false
        default: false
        type: boolean
      existing_image_tag:
        description: 'Existing image tag to deploy (when skip_build is true)'
        required: false
        type: string
      deploy_branch:
        description: 'Branch to deploy from'
        required: false
        default: 'main'
        type: string

jobs:
  # Get configuration
  config:
    uses: ./.github/workflows/config.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      instance_name: ${{ github.event.inputs.instance_name }}

  # Conditionally build Docker image
  build:
    needs: config
    if: ${{ !github.event.inputs.skip_build }}
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ needs.config.outputs.environment }}
      instance_name: ${{ needs.config.outputs.instance_name }}
    secrets: inherit
  
  # Deploy to VPS
  deploy:
    needs: [config, build]
    uses: ./.github/workflows/deploy-vps.yml
    with:
      environment: ${{ needs.config.outputs.environment }}
      instance_name: ${{ needs.config.outputs.instance_name }}
      image_tag: ${{ github.event.inputs.skip_build == true && github.event.inputs.existing_image_tag || needs.build.outputs.image_tag }}
    secrets: inherit 