name: Prepare
on:
  workflow_call:
    outputs:
      services:
        description: "Parsed services from config file"
        value: ${{ jobs.prepare.outputs.services }}
      service_names:
        description: "Names of services to build"
        value: ${{ jobs.prepare.outputs.service_names }}

env:
  CONFIG_FILE: .github/build-config.json

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.parse-config.outputs.services }}
      service_names: ${{ steps.parse-names.outputs.names }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Parse build configuration
      id: parse-config
      run: |
        chmod +x .github/scripts/parse-config.sh
        ./.github/scripts/parse-config.sh